spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: ${DATABASE_URL}
        username: ${DATABASE_USERNAME}
        password: ${DATABASE_PASSWORD}
    
    main:
        allow-circular-references: true

mybatis:
    configuration:
        map-underscore-to-camel-case: true

app:
    jwt:
        secret: ${JWT_SECRET}
        expiration-in:
            ms: ${JTW_EXPIRATION}