spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/book_seller_db?currentSchema=book_seller_sc&ssl=false
        username: admin
        password: password
    
    main:
        allow-circular-references: true

mybatis:
    configuration:
        map-underscore-to-camel-case: true

app:
    jwt:
        secret: ${JWT_SECRET}
        expiration-in:
            ms: 86400000